# Generated by Django 5.0.2 on 2024-02-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_recipecommentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='likes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='RecipeCommentReply',
        ),
    ]
