# Generated by Django 5.0.2 on 2024-02-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
        ('recipes', '0003_delete_recipecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='diet.diet'),
        ),
    ]
