# Generated by Django 5.0.2 on 2024-02-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('recipes', '0004_recipe_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='course',
        ),
        migrations.AddField(
            model_name='recipe',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='courses.course'),
        ),
    ]
